import type { AppDatabase } from '../shared/database'
import type { PerformanceRecord } from './performance-record.schema'

type Row = { id:string; publishing_task_id:string|null; product_name:string; platform:'小红书'|'抖音'; title:string; recorded_on:string; impressions:number; views:number; likes:number; favorites:number; comments:number; shares:number; leads:number; orders:number; revenue:number; created_at:string; updated_at:string }
const map = (r:Row):PerformanceRecord => ({ id:r.id, publishingTaskId:r.publishing_task_id, productName:r.product_name, platform:r.platform, title:r.title, recordedOn:r.recorded_on, impressions:r.impressions, views:r.views, likes:r.likes, favorites:r.favorites, comments:r.comments, shares:r.shares, leads:r.leads, orders:r.orders, revenue:r.revenue, createdAt:r.created_at, updatedAt:r.updated_at })
export function createPerformanceRecordRepository(database:AppDatabase) { return {
  list(query:{platform:string;productName:string}) { const clauses:string[]=[]; const values:string[]=[]; if(query.platform){clauses.push('platform=?');values.push(query.platform)} if(query.productName){clauses.push('product_name LIKE ?');values.push(`%${query.productName}%`)} return (database.prepare(`SELECT * FROM performance_records ${clauses.length?`WHERE ${clauses.join(' AND ')}`:''} ORDER BY recorded_on DESC`).all(...values) as Row[]).map(map) },
  find(id:string){const row=database.prepare('SELECT * FROM performance_records WHERE id=?').get(id) as Row|undefined;return row?map(row):null},
  save(r:PerformanceRecord){database.prepare(`INSERT INTO performance_records VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET publishing_task_id=excluded.publishing_task_id,product_name=excluded.product_name,platform=excluded.platform,title=excluded.title,recorded_on=excluded.recorded_on,impressions=excluded.impressions,views=excluded.views,likes=excluded.likes,favorites=excluded.favorites,comments=excluded.comments,shares=excluded.shares,leads=excluded.leads,orders=excluded.orders,revenue=excluded.revenue,updated_at=excluded.updated_at`).run(r.id,r.publishingTaskId,r.productName,r.platform,r.title,r.recordedOn,r.impressions,r.views,r.likes,r.favorites,r.comments,r.shares,r.leads,r.orders,r.revenue,r.createdAt,r.updatedAt);return r},
  remove(id:string){return database.prepare('DELETE FROM performance_records WHERE id=?').run(id).changes>0},
  replaceAll(records:PerformanceRecord[]){database.exec('BEGIN');try{database.prepare('DELETE FROM performance_records').run();records.forEach(record=>this.save(record));database.exec('COMMIT')}catch(error){database.exec('ROLLBACK');throw error}},
} }
