import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { BarChart3, Database, FileUp, Plus, Trash2, TrendingUp } from 'lucide-react'
import { publishingTasksApi, type PublishingTask } from '../publishing-tasks/publishing-tasks.api'
import { performanceApi, type PerformanceDraft, type PerformanceRecord } from './performance.api'
import { byPlatform, demoPerformance, summarize } from './performance'
import { CsvImportPanel } from './CsvImportPanel'
import './analytics-dashboard.css'

const empty=():PerformanceDraft=>({publishingTaskId:null,productName:'',platform:'小红书',title:'',recordedOn:new Date().toISOString().slice(0,10),impressions:0,views:0,likes:0,favorites:0,comments:0,shares:0,leads:0,orders:0,revenue:0})
const metricFields:Array<[keyof PerformanceDraft,string]>=[['impressions','曝光量'],['views','播放/阅读'],['likes','点赞'],['favorites','收藏'],['comments','评论'],['shares','分享'],['leads','线索'],['orders','订单'],['revenue','成交额']]
const compact=(value:number)=>new Intl.NumberFormat('zh-CN',{notation:'compact',maximumFractionDigits:1}).format(value)
const percent=(value:number)=>`${(value*100).toFixed(2)}%`

export function AnalyticsDashboard({onNotice}:{onNotice:(message:string)=>void}){
  const [saved,setSaved]=useState<PerformanceRecord[]>([]);const [tasks,setTasks]=useState<PublishingTask[]>([]);const [showForm,setShowForm]=useState(false);const [showImport,setShowImport]=useState(false);const [draft,setDraft]=useState<PerformanceDraft>(empty);const [loading,setLoading]=useState(true)
  useEffect(()=>{void Promise.all([performanceApi.list(),publishingTasksApi.list({status:'published'})]).then(([records,published])=>{setSaved(records.data);setTasks(published.data)}).catch(error=>onNotice(error instanceof Error?error.message:'复盘数据加载失败')).finally(()=>setLoading(false))},[onNotice])
  const records=saved.length?saved:demoPerformance;const summary=useMemo(()=>summarize(records),[records]);const platforms=useMemo(()=>byPlatform(records),[records]);const maxViews=Math.max(...platforms.map(item=>item.views),1)
  const chooseTask=(id:string)=>{const task=tasks.find(item=>item.id===id);if(task)setDraft(current=>({...current,publishingTaskId:task.id,productName:task.productName,platform:task.platform,title:task.title}))}
  const save=async(event:FormEvent)=>{event.preventDefault();try{const result=await performanceApi.create(draft);setSaved(current=>[result.data,...current]);setDraft(empty());setShowForm(false);onNotice('作品表现数据已保存')}catch(error){onNotice(error instanceof Error?error.message:'表现数据保存失败')}}
  const remove=async(record:PerformanceRecord)=>{if(!confirm(`删除“${record.title}”的表现记录？`))return;await performanceApi.remove(record.id);setSaved(current=>current.filter(item=>item.id!==record.id));onNotice('表现记录已删除')}
  return <section className="analytics-page"><header className="analytics-head"><div><p>内容经营复盘</p><h1>数据复盘</h1><span>用真实互动和转化数据，判断下一条内容该继续什么。</span></div><div className="analytics-head-actions"><button onClick={()=>setShowImport(true)}><FileUp size={18}/>导入 CSV</button><button className="primary" onClick={()=>setShowForm(true)}><Plus size={18}/>录入作品数据</button></div></header>
    {!saved.length&&!loading&&<div className="demo-banner"><Database size={17}/><span>当前展示模拟数据；录入第一条真实数据后会自动替换。</span></div>}
    {showImport&&<CsvImportPanel onClose={()=>setShowImport(false)} onImported={records=>setSaved(current=>[...records,...current])} onNotice={onNotice}/>}
    <div className="metric-grid"><Metric label="播放/阅读" value={compact(summary.views)} note="内容有效触达"/><Metric label="互动率" value={percent(summary.engagementRate)} note={`${compact(summary.interactions)} 次互动`}/><Metric label="订单转化率" value={percent(summary.conversionRate)} note={`${summary.orders} 笔订单`}/><Metric label="成交额" value={`¥${summary.revenue.toFixed(0)}`} note="内容归因成交"/></div>
    {showForm&&<form className="analytics-form" onSubmit={save}><div><h2>录入作品表现</h2><button type="button" onClick={()=>setShowForm(false)}>取消</button></div><label>关联已发布任务<select aria-label="关联已发布任务" value={draft.publishingTaskId??''} onChange={event=>chooseTask(event.target.value)}><option value="">不关联，手动填写</option>{tasks.map(task=><option key={task.id} value={task.id}>{task.productName} · {task.title}</option>)}</select></label><div className="analytics-form-grid"><label>商品名称<input required aria-label="表现商品名称" value={draft.productName} onChange={event=>setDraft({...draft,productName:event.target.value})}/></label><label>平台<select aria-label="表现平台" value={draft.platform} onChange={event=>setDraft({...draft,platform:event.target.value as PerformanceDraft['platform']})}><option>小红书</option><option>抖音</option></select></label><label>作品标题<input required aria-label="表现作品标题" value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label>统计日期<input required aria-label="统计日期" type="date" value={draft.recordedOn} onChange={event=>setDraft({...draft,recordedOn:event.target.value})}/></label>{metricFields.map(([field,label])=><label key={field}>{label}<input required aria-label={label} type="number" min="0" step={field==='revenue'?'0.01':'1'} value={draft[field] as number} onChange={event=>setDraft({...draft,[field]:Number(event.target.value)})}/></label>)}</div><button className="primary">保存表现数据</button></form>}
    <div className="analytics-layout"><section className="platform-panel"><h2>平台表现对比</h2>{platforms.map(item=><article key={item.platform}><div><strong>{item.platform}</strong><span>{compact(item.views)} 播放 · {item.orders} 订单</span></div><div className="bar"><i style={{width:`${item.views/maxViews*100}%`}}/></div><b>{percent(item.engagementRate)} 互动率</b></article>)}</section><section className="ranking-panel"><h2>作品表现排行</h2><div className="ranking-head"><span>作品</span><span>播放</span><span>互动率</span><span>订单</span></div>{[...records].sort((a,b)=>b.views-a.views).map((record,index)=><article key={record.id}><b>{index+1}</b><div><strong>{record.title}</strong><small>{record.platform} · {record.productName}</small></div><span>{compact(record.views)}</span><span>{percent(summarize([record]).engagementRate)}</span><span>{record.orders}</span>{saved.length>0&&<button aria-label={`删除 ${record.title}`} onClick={()=>void remove(record)}><Trash2 size={14}/></button>}</article>)}</section></div>
  </section>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <article><div><BarChart3 size={17}/><span>{label}</span></div><strong>{value}</strong><small><TrendingUp size={13}/>{note}</small></article>}
